### ISSUE TITLE
sitemap.xml kann auch in anderen Verzeichnissen liegen

### ISSUE THREAD

**Issue by donfalconedd** [tyclipso/seo-ninja#1]
Moin ihr Tyconauten,

der Test der sitemap.xml könnte verbessert werden. Diese muss nicht zwangsläufig im Webroot liegen. Bei Contao wird sie z.B. immer im Verzeichnis share abgelegt.  In die robots.txt kann man den Pfad hinterlegen:

Sitemap: http://www.domain.de/share/sitemap.xml

Ansonsten, nettes Tool, weiter so!
Grüße
Falko

**Comment by ghost** [comment]
Danke für den Hinweis.
Hast du ein konkretes Beispiel, wo ich diesen Fall nachstellen kann?

**Comment by donfalconedd** [comment]
Aber sicher doch, und zwar hier: 

http://www.hybrilog.de/share/sitemap.xml
http://www.hybrilog.de/robots.txt

**Comment by ghost** [comment]
Der SEO Ninja wurde mit der Version 1.3.4 dahingehend erweitert. Findet er keine sitemap.xml im Root der Website, dann schaut er nach, ob er eine sitemap in der robots.txt findet und nimmt diese.
